version: '3.4'
services:
  puppetfilechecker:
    image: docker.tom-krieger.de/puppetfile-version-checker-api:0.1.4
    ports:
      - "0.0.0.0:9120:80"
    networks:
      puppetfilecheckerapi:
        aliases:
          - puppetfilecheckerapi
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DEBUG=0
    deploy:
      mode: global
      # replicas: 4
networks:
  puppetfilecheckerapi: